**Soal No.1**

In [ ]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy

In [ ]:
import numpy as np

In [ ]:
X = np.array([[12, 86, 43],
              [87, 51, 23]])
X

array([[12, 86, 43],
       [87, 51, 23]])

In [ ]:
#Buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[56, 12, 34],
                     [56, 43, 87]])
X_pt

tensor([[56, 12, 34],
        [56, 43, 87]])

In [ ]:
#Buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.constant([[19, 91, 67],
                    [69, 42, 21]])
X_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, 91, 67],
       [69, 42, 21]], dtype=int32)>

In [ ]:
#lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar

In [ ]:
skalar = 2

X_s = X * skalar
X_pt_s = X_pt * skalar
X_tf_s = X_tf * skalar

print("Matriks X (numpy) setelah perkalian dengan skalar:")
print(X_s)
print()
print("Matriks X (PyTorch) setelah perkalian dengan skalar:")
print(X_pt_s)
print()
print("Matriks X (TensorFlow) setelah perkalian dengan skalar:")
print(X_tf_s)

Matriks X (numpy) setelah perkalian dengan skalar:
[[ 24 172  86]
 [174 102  46]]

Matriks X (PyTorch) setelah perkalian dengan skalar:
tensor([[112,  24,  68],
        [112,  86, 174]])

Matriks X (TensorFlow) setelah perkalian dengan skalar:
tf.Tensor(
[[ 38 182 134]
 [138  84  42]], shape=(2, 3), dtype=int32)


**Soal No.2**

In [ ]:
#Buat matrix Y dengan ukuran 2x3 menggunakan numpy

In [ ]:
Y = np.array([[1, 3, 4],
              [6, 5, 8]])
Y

array([[1, 3, 4],
       [6, 5, 8]])

In [ ]:
#Buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch

In [ ]:
Y_pt = torch.tensor([[2, 9, 5],
                     [7, 5, 8]])
Y_pt

tensor([[2, 9, 5],
        [7, 5, 8]])

In [ ]:
#Buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow

In [ ]:
Y_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])
Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
#Kalikan matrix X dengan Y

In [ ]:
X_Y = X * Y
X_Y

array([[ 12, 258, 172],
       [522, 255, 184]])

In [ ]:
#Kalikan matrix X_pt dengan Y_pt

In [ ]:
X_pt_Y_pt = X_pt * Y_pt
X_pt_Y_pt

tensor([[112, 108, 170],
        [392, 215, 696]])

In [ ]:
#Kalikan matrix X_tf dengan Y_tf

In [ ]:
X_tf_Y_tf = X_tf * Y_tf
X_tf_Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 19, 182, 201],
       [276, 210, 126]], dtype=int32)>