**Soal No.1**

In [28]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy

In [29]:
import numpy as np

In [30]:
X = np.array([[12, 86, 43],
              [87, 51, 23]])
X

array([[12, 86, 43],
       [87, 51, 23]])

In [31]:
#Buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch

In [32]:
import torch

In [33]:
X_pt = torch.tensor([[56, 12, 34],
                     [56, 43, 87]])
X_pt

tensor([[56, 12, 34],
        [56, 43, 87]])

In [34]:
#Buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [35]:
import tensorflow as tf

In [36]:
X_tf = tf.constant([[19, 91, 67],
                    [69, 42, 21]])
X_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, 91, 67],
       [69, 42, 21]], dtype=int32)>

In [37]:
#lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar

In [38]:
skalar = 2

X_s = X * skalar
X_pt_s = X_pt * skalar
X_tf_s = X_tf * skalar

print("Matriks X (numpy) setelah perkalian dengan skalar:")
print(X_s)
print()
print("Matriks X (PyTorch) setelah perkalian dengan skalar:")
print(X_pt_s)
print()
print("Matriks X (TensorFlow) setelah perkalian dengan skalar:")
print(X_tf_s)

Matriks X (numpy) setelah perkalian dengan skalar:
[[ 24 172  86]
 [174 102  46]]

Matriks X (PyTorch) setelah perkalian dengan skalar:
tensor([[112,  24,  68],
        [112,  86, 174]])

Matriks X (TensorFlow) setelah perkalian dengan skalar:
tf.Tensor(
[[ 38 182 134]
 [138  84  42]], shape=(2, 3), dtype=int32)


In [39]:
#lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar

In [40]:
X_p = X - skalar
X_pt_p = X_pt - skalar
X_tf_p = X_tf - skalar

print("Matriks X (numpy) setelah pengurangan dengan skalar:")
print(X_p)
print()
print("Matriks X (PyTorch) setelah pengurangan dengan skalar:")
print(X_pt_p)
print()
print("Matriks X (TensorFlow) setelah pengurangan dengan skalar:")
print(X_tf_p)

Matriks X (numpy) setelah pengurangan dengan skalar:
[[10 84 41]
 [85 49 21]]

Matriks X (PyTorch) setelah pengurangan dengan skalar:
tensor([[54, 10, 32],
        [54, 41, 85]])

Matriks X (TensorFlow) setelah pengurangan dengan skalar:
tf.Tensor(
[[17 89 65]
 [67 40 19]], shape=(2, 3), dtype=int32)


In [41]:
#lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar

In [42]:
X_t = X + skalar
X_pt_t = X_pt + skalar
X_tf_t = X_tf + skalar

print("Matriks X (numpy) setelah penambahan dengan skalar:")
print(X_t)
print()
print("Matriks X (PyTorch) setelah penambahan dengan skalar:")
print(X_pt_t)
print()
print("Matriks X (TensorFlow) setelah penambahan dengan skalar:")
print(X_tf_t)

Matriks X (numpy) setelah penambahan dengan skalar:
[[14 88 45]
 [89 53 25]]

Matriks X (PyTorch) setelah penambahan dengan skalar:
tensor([[58, 14, 36],
        [58, 45, 89]])

Matriks X (TensorFlow) setelah penambahan dengan skalar:
tf.Tensor(
[[21 93 69]
 [71 44 23]], shape=(2, 3), dtype=int32)


**Soal No.2**

In [43]:
#Buat matrix Y dengan ukuran 2x3 menggunakan numpy

In [44]:
Y = np.array([[1, 3, 4],
              [6, 5, 8]])
Y

array([[1, 3, 4],
       [6, 5, 8]])

In [45]:
#Buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch

In [46]:
Y_pt = torch.tensor([[2, 9, 5],
                     [7, 5, 8]])
Y_pt

tensor([[2, 9, 5],
        [7, 5, 8]])

In [47]:
#Buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow

In [48]:
Y_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])
Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [49]:
#Kalikan matrix X dengan Y

In [50]:
X_Y = X * Y
X_Y

array([[ 12, 258, 172],
       [522, 255, 184]])

In [51]:
#Kalikan matrix X_pt dengan Y_pt

In [52]:
X_pt_Y_pt = X_pt * Y_pt
X_pt_Y_pt

tensor([[112, 108, 170],
        [392, 215, 696]])

In [53]:
#Kalikan matrix X_tf dengan Y_tf

In [54]:
X_tf_Y_tf = X_tf * Y_tf
X_tf_Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 19, 182, 201],
       [276, 210, 126]], dtype=int32)>