Soal Nomor 1

In [31]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy

In [32]:
import numpy as np

In [33]:
X = np.array([[17, 5, 10], [13, 9, 2]])
X

array([[17,  5, 10],
       [13,  9,  2]])

In [34]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

np.int64(56)

In [35]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [36]:
import tensorflow as tf

In [37]:
X_tf = tf.Variable([[17, 5, 10], [13, 9, 2]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[17,  5, 10],
       [13,  9,  2]], dtype=int32)>

Soal Nomor 2

In [38]:
# hitung hasil penjumlahan seluruh elemen matrix X
X.sum()

np.int64(56)

In [39]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt

In [40]:
import torch

In [41]:
X_pt = torch.tensor([[17, 5, 10], [13, 9, 2]])
X_pt

tensor([[17,  5, 10],
        [13,  9,  2]])

In [42]:
torch.sum(X_pt)

tensor(56)

In [43]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=56>

Soal Nomor 3

In [44]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X.sum(axis=1)

array([32, 24])

In [45]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
torch.sum(X_pt, 1)

tensor([32, 24])

In [46]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([32, 24], dtype=int32)>

Soal Nomor 4

In [47]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(axis=0)

array([30, 14, 12])

In [48]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
torch.sum(X_pt, 0)

tensor([30, 14, 12])

In [49]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([30, 14, 12], dtype=int32)>

Soal Nomor 5

In [50]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
X.min()

np.int64(2)

In [51]:
X_pt.min()

tensor(2)

In [52]:
tf.reduce_min(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [53]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X.max()

np.int64(17)

In [54]:
X_pt.max()

tensor(17)

In [55]:
tf.reduce_max(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [56]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X.mean()

np.float64(9.333333333333334)

In [57]:
X_pt.float().mean()

tensor(9.3333)

In [58]:
tf.reduce_mean(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

Soal Nomor 6

In [59]:
# hitung hasil perkalian seluruh elemen matrix X
X.prod()

np.int64(198900)

In [60]:
# hitung hasil perkalian seluruh elemen matrix X_pt
X_pt.prod()

tensor(198900)

In [61]:
# hitung hasil perkalian seluruh elemen matrix X_tf
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=198900>