**Soal No.1**

In [ ]:
#Buat matrix X dengan ukuran 2x3 menggunakan numpy

In [ ]:
import numpy

In [ ]:
X = numpy.array([[70, 45, 15], [55, 63, 34]])
X

array([[70, 45, 15],
       [55, 63, 34]])

In [ ]:
#Buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[34, 12, 54], [74, 42, 54]])
X_pt

tensor([[34, 12, 54],
        [74, 42, 54]])

In [ ]:
#Buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.constant([[59, 73, 69], [53, 47, 57]])
X_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[59, 73, 69],
       [53, 47, 57]], dtype=int32)>

2. Lakukan transpose pada matrix X, X_pt dan X_tf

In [ ]:
print("Transpose matriks X : ")
print(X.T)
print()
print("Transpose matriks X_pt : ")
print(X_pt.T)
print()
print("Transpose matriks X_tf : ")
print(tf.transpose(X_tf))

Transpose matriks X : 
[[70 55]
 [45 63]
 [15 34]]

Transpose matriks X_pt : 
tensor([[34, 74],
        [12, 42],
        [54, 54]])

Transpose matriks X_tf : 
tf.Tensor(
[[59 53]
 [73 47]
 [69 57]], shape=(3, 2), dtype=int32)
