Soal Nomor 1

In [ ]:
# buat vector x dan y dengan ukuran 1x3 menggunakan numpy
import numpy as np

In [ ]:
x = np.array([13, 24, 8])
x

array([13, 24,  8])

In [ ]:
y = np.array([2, 11, 20])
y

array([ 2, 11, 20])

In [ ]:
# buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
import torch

In [ ]:
x_pt = torch.tensor([13, 24, 8])
x_pt

tensor([13, 24,  8])

In [ ]:
y_pt = torch.tensor([2, 11, 20])
y_pt

tensor([ 2, 11, 20])

In [ ]:
# buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
import tensorflow as tf

In [ ]:
x_tf = tf.Variable([13, 24, 8])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([13, 24,  8], dtype=int32)>

In [ ]:
y_tf = tf.Variable([2, 11, 20])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 2, 11, 20], dtype=int32)>

Soal Nomor 2

In [ ]:
# hitung perkalian dot product antara vector x dan vector y
np.dot(x, y)

np.int64(450)

In [ ]:
# hitung perkalian dot product antara vector x_pt dan vector y_pt
torch.dot(x_pt, y_pt)

tensor(450)

In [ ]:
# hitung perkalian dot product antara vector x_tf dan vector y_tf
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=450>

Soal Nomor 3

In [ ]:
# lakukan perhitungan excercise menggunakan collab

bagian 1

In [ ]:
Y = np.array([[42, 4, 7, 99],
              [-99, -3, 17, 22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [ ]:
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

bagian 2

In [ ]:
A = np.array([[25, 10],
              [-2, 1]])
A

array([[25, 10],
       [-2,  1]])

In [ ]:
B = np.array([[-1, 7],
              [10, 8]])
B

array([[-1,  7],
       [10,  8]])

In [ ]:
A * B

array([[-25,  70],
       [-20,   8]])

bagian 3

In [ ]:
w = [-1, 2, -2]
w

[-1, 2, -2]

In [ ]:
x = [5, 10, 0]
x

[5, 10, 0]

In [ ]:
np.dot(w, x)

np.int64(15)