In [24]:
import numpy as np

In [25]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 15, 6], [1, 0, 5]])
X

array([[25, 15,  6],
       [ 1,  0,  5]])

In [23]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [26]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X.size

6

In [27]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([1, 0, 5])

2. ulangi soal nomor 1 menggunakan Pytorch

In [28]:
import torch

In [29]:
X_pt = torch.tensor([[25, 15, 6], [1, 0, 5]])
X_pt

tensor([[25, 15,  6],
        [ 1,  0,  5]])

In [30]:
X_pt.shape

torch.Size([2, 3])

In [31]:
X_pt.size

<function Tensor.size>

In [32]:
X_pt[1,:]

tensor([1, 0, 5])

3. ulangi soal nomor 1 menggunakan Tensorflow

In [33]:
import tensorflow as tf

In [34]:
X_tf = tf.Variable([[25, 15, 6], [1, 0, 5]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15,  6],
       [ 1,  0,  5]], dtype=int32)>

In [43]:
X_tf.shape

TensorShape([2, 3])

In [44]:
tf.size(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [45]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 5], dtype=int32)>