In [12]:
import numpy as np

In [13]:
# buat vector x dengan ukuran 3x1
x = np.array([[1],
              [0],
              [6]])
x

array([[1],
       [0],
       [6]])

In [14]:
x

array([[1],
       [0],
       [6]])

In [15]:
# hitung nilai L2 norm dari vector x
(1**2 + 0**2 + 6**2)

37

2. buat vector v dengan elemen (3,4)

In [16]:
v = np.array([[3],
              [4]])
v

array([[3],
       [4]])

In [17]:
# hitung nilai L2 norm dari vector v
(3**2 + 4**2)

25

In [20]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(v)
unit_v = v / norm
unit_v

array([[0.6],
       [0.8]])

In [22]:
# hitung panjang unit vector dari vector v
np.linalg.norm(unit_v)

np.float64(1.0)