In [2]:
import numpy as np

In [25]:
# buat vector x dengan ukuran 3x1
x = np.array([[1],
              [0],
              [5]])
x

array([[1],
       [0],
       [5]])

In [26]:
# hitung panjang vector x
len(x)

3

In [27]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [28]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [29]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

array([1])

In [30]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. lakukan transpose pada vector x dan simpan pada variabel x_t

In [31]:
x_t = x.T
x_t

array([[1, 0, 5]])

In [32]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [33]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[6],
              [0],
              [5]])

y_t = y.T
y_t

array([[6, 0, 5]])

In [13]:
# tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [34]:
import torch as pt

In [36]:
x = pt.tensor([[1],
               [0],
               [5]])
x

tensor([[1],
        [0],
        [5]])

In [37]:
x_t = x.T
x_t

tensor([[1, 0, 5]])

In [38]:
x_t.shape

torch.Size([1, 3])

In [40]:
y = pt.tensor([[6],
               [0],
               [5]])
y

tensor([[6],
        [0],
        [5]])

In [41]:
y_t = y.T
y_t

tensor([[6, 0, 5]])

In [42]:
import tensorflow as tf

In [43]:
x = tf.constant([[1],
                 [0],
                 [5]])
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [0],
       [6]], dtype=int32)>

In [22]:
x_t = tf.transpose(x)
x_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 0, 6]], dtype=int32)>

In [44]:
y = tf.constant([[6],
                 [0],
                 [5]])
y

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[6],
       [0],
       [5]], dtype=int32)>

In [45]:
y_t = tf.transpose(y)
y_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[6, 0, 5]], dtype=int32)>