In [ ]:
import numpy as np

In [ ]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 15, 6], [1, 0, 5]])
X

array([[25, 15,  6],
       [ 1,  0,  5]])

In [ ]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [ ]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([25,  1])

In [ ]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([1, 0, 5])

2. ulangi soal nomor 1 menggunakan Pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[25, 15, 6], [1, 0, 5]])
X_pt

tensor([[25, 15,  6],
        [ 1,  0,  5]])

In [ ]:
X_pt.shape

torch.Size([2, 3])

In [ ]:
X_pt[:,0]

tensor([25,  1])

In [ ]:
X_pt[1,:]

tensor([1, 0, 5])

3. ulangi soal nomor 1 menggunakan Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[25, 15, 6], [1, 0, 5]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15,  6],
       [ 1,  0,  5]], dtype=int32)>

In [ ]:
X_tf.shape

TensorShape([2, 3])

In [ ]:
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25,  1], dtype=int32)>

In [ ]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 5], dtype=int32)>