In [1]:
#Menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm

NumPy

In [2]:
import numpy as np

In [3]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
(1**2 + 2**2 + 3**2 + 4**2 + 5**2 + 6**2 + 7**2 + 8**2 + 9**2)**(1/2)

16.881943016134134

In [5]:
frob = np.linalg.norm(X)

In [17]:
print("Matrix:\n", X)
print()
print("Frobenius Norm:", frob)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Frobenius Norm: 16.881943016134134


PyTorch

In [7]:
import torch as pt

In [8]:
X_pt = pt.tensor([[5, 4, 3],
                  [4, 5, 6],
                  [8, 4, 2]])
X_pt

tensor([[5, 4, 3],
        [4, 5, 6],
        [8, 4, 2]])

In [9]:
frobpt = pt.norm(X_pt.float())

In [19]:
print("Matrix:\n", X_pt)
print()
print("Frobenius Norm:", frobpt)

Matrix:
 tensor([[5, 4, 3],
        [4, 5, 6],
        [8, 4, 2]])

Frobenius Norm: tensor(14.5258)


TensorFlow

In [11]:
import tensorflow as tf

In [12]:
X_tf = tf.constant([[7, 2, 5],
                    [4, 5, 6],
                    [3, 8, 0]])
X_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 2, 5],
       [4, 5, 6],
       [3, 8, 0]], dtype=int32)>

In [13]:
frobtf = tf.Variable(X_tf)

In [18]:
print("Matrix:\n", X_tf)
print()
print("Frobenius Norm:", frobtf)

Matrix:
 tf.Tensor(
[[7 2 5]
 [4 5 6]
 [3 8 0]], shape=(3, 3), dtype=int32)

Frobenius Norm: <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[7, 2, 5],
       [4, 5, 6],
       [3, 8, 0]], dtype=int32)>
