### Matrix Inversion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[8, 3], [-5, -9]])
X

array([[ 8,  3],
       [-5, -9]])

In [ ]:
# buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[ 0.15789474,  0.05263158],
       [-0.0877193 , -0.14035088]])

In [ ]:
# kalikan X dengan Xinv menggunakan numpy
np.dot(Xinv, X)

array([[1., 0.],
       [0., 1.]])

Penyelesaian menggunakan PyTorch dan TensorFlow:

In [ ]:
# selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

In [ ]:
# penyelesaian menggunakan numpy

# buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [ ]:
# buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [ ]:
# kalikan X dengan Xinv menggunakan numpy
np.dot(Xinv, X)

array([[1.00000000e+00, 3.33066907e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [ ]:
# buat matrix y menggunakan numpy
y = np.array([4, -7])
y

array([ 4, -7])

In [ ]:
# cari nilai w
w = np.dot(Xinv, y)
w

array([-1.,  4.])

In [ ]:
# penyelesaian menggunakan TensorFlow
X_inv_tf = tf.linalg.inv(tf.Variable([[4, 2], [-5, -3.]])) # also float
X_inv_tf
w_tf = tf.linalg.matvec(X_inv_tf, y_tf)
w_tf

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.9999995,  3.999999 ], dtype=float32)>

In [ ]:
# penyelesaian menggunakan PyTorch
X_inv_torch = torch.inverse(torch.tensor([[4, 2], [-5, -3.]])) # float type
X_inv_torch
w_torch = torch.matmul(X_inv_torch, y_torch)
w_torch

tensor([-1.,  4.])