Soal No. 1

In [25]:
#Buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy

In [26]:
import numpy as np

In [27]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b = np.array([[1],
              [2],
              [3]])
b

array([[1],
       [2],
       [3]])

In [29]:
#Buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch

In [30]:
import torch as pt

In [31]:
A_pt = pt.tensor([[5, 4, 6],
                  [8, 6, 5]])
A_pt

tensor([[5, 4, 6],
        [8, 6, 5]])

In [32]:
b_pt = pt.tensor([[4],
                  [2],
                  [7]])
b_pt

tensor([[4],
        [2],
        [7]])

In [33]:
#Buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow

In [34]:
import tensorflow as tf

In [35]:
A_tf = tf.Variable([[5, 7, 8],
                    [4, 5, 3]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 7, 8],
       [4, 5, 3]], dtype=int32)>

In [36]:
b_tf = tf.Variable([[1],
                    [2],
                    [9]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [9]], dtype=int32)>

Soal No. 2

In [ ]:
#Tampilkan ukuran matrix A dan vector b

NumPy

In [37]:
A.shape

(2, 3)

In [38]:
b.shape

(3, 1)

PyTorch

In [39]:
A_pt.shape

torch.Size([2, 3])

In [40]:
b_pt.shape

torch.Size([3, 1])

TensorFlow

In [41]:
A_tf.shape

TensorShape([2, 3])

In [42]:
b_tf.shape

TensorShape([3, 1])

Soal No. 3

In [ ]:
#Kalikan matrix A dengan vector b

In [43]:
np.dot(A, b)

array([[14],
       [32]])

In [44]:
#kalikan matrix A_pt dengan vector b_pt

In [45]:
pt.matmul(A_pt, b_pt)

tensor([[70],
        [79]])

In [46]:
#kalikan matrix A_tf dengan vector b_tf

In [47]:
tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[91],
       [41]], dtype=int32)>

Soal No. 4

In [ ]:
#Buat matrix B dengan ukuran 3x3 menggunakan numpy

In [48]:
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
#buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch

In [54]:
B_pt = pt.tensor([[5, 3, 2],
                  [8, 5, 3],
                  [9, 4, 6]])
B_pt

tensor([[5, 3, 2],
        [8, 5, 3],
        [9, 4, 6]])

In [ ]:
#buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow

In [53]:
B_tf = tf.Variable([[0, 3, 7],
                    [8, 2, 3],
                    [5, 4, 6]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 3, 7],
       [8, 2, 3],
       [5, 4, 6]], dtype=int32)>

Soal No. 5

In [ ]:
#kalikan matrix A dengan matrix B

In [55]:
np.dot(A, B)

array([[30, 36, 42],
       [66, 81, 96]])

In [ ]:
#kalikan matrix A_pt dengan matrix B_pt

In [56]:
pt.matmul(A_pt, B_pt)

tensor([[111,  59,  58],
        [133,  74,  64]])

In [ ]:
#kalikan matrix A_tf dengan matrix B_tf

In [57]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 96,  61, 104],
       [ 55,  34,  61]], dtype=int32)>

In [ ]:
#buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

In [62]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [60]:
np.dot(A, B)

array([[30, 36, 42],
       [66, 81, 96]])

In [63]:
# np.dot(B, A)  Jika  "#" dihapus akan terjadi error karena tidak valid → size mismatch error

In [ ]:
#Jadi kesimpulannya idak semua perkalian Matrix bersifat komutatif