Soal No. 1

In [17]:
#buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

In [18]:
import numpy as np

In [32]:
A_sym = np.array([[2, 4, 6],
                  [4, 5, 7],
                  [6, 7, 9]])
A_sym

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [26]:
print("Transpose:\n", A_sym.T)
print()
print("Apakah simetris?", np.array_equal(A_sym, A_sym.T))

Transpose:
 [[2 4 6]
 [4 5 7]
 [6 7 9]]

Apakah simetris? True


Soal No.2

In [21]:
#menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4

In [34]:
import torch

In [40]:
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [41]:
print("Transpose:\n", I.T)
print()
print("Apakah simetris?", np.array_equal(I, I.T))

Transpose:
 tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

Apakah simetris? True


In [ ]:
#menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1

In [43]:
b_pt = torch.tensor([[2], [6], [8], [9]])
b_pt

tensor([[2],
        [6],
        [8],
        [9]])

In [ ]:
#kalikan matrix I dengan vector b_pt

In [45]:
torch.matmul(I, b_pt)

tensor([[2],
        [6],
        [8],
        [9]])